cqframework/cqf-ruler

- src/main/java/org/opencds/cqf/evaluation/MeasureEvaluation.java
- src/main/java/org/opencds/cqf/helpers/DataProviderHelper.java
- src/main/java/org/opencds/cqf/providers/BundleDataProviderStu3.java
- src/main/java/org/opencds/cqf/providers/FHIRMeasureResourceProvider.java
- src/test/java/org/opencds/cqf/MeasureEvaluationTests.java
- src/test/java/org/opencds/cqf/TestBase.java
- src/test/resources/org/opencds/cqf/measure-evaluation/col-source-data-bundle.json
This pull request is for an enhancement to the measure resource provider. I added an operation called $evaluate-measure-with-source that evaluates the measure using a passed in Bundle of source data. Currently only supporting patient-level evaluation.
> #48 - source data measure evaluation

- pom.xml
- src/main/java/ca/uhn/fhir/rest/server/method/BaseResourceReturningMethodBinding.java
- src/main/java/org/opencds/cqf/bulkdata/BulkDataRequest.java
- src/main/java/org/opencds/cqf/bulkdata/BulkDataResponse.java
- src/main/java/org/opencds/cqf/config/FhirServerConfigDstu2.java
- src/main/java/org/opencds/cqf/config/FhirServerConfigDstu3.java
- src/main/java/org/opencds/cqf/config/FhirServerConfigR4.java
- src/main/java/org/opencds/cqf/helpers/BulkDataHelper.java
- src/main/java/org/opencds/cqf/providers/BulkDataGroupProvider.java
- src/main/java/org/opencds/cqf/providers/BulkDataPatientProvider.java
- src/main/java/org/opencds/cqf/providers/FHIRMeasureResourceProvider.java
- src/main/java/org/opencds/cqf/providers/JpaDataProvider.java
- src/main/java/org/opencds/cqf/providers/R4MeasureResourceProvider.java
- src/main/java/org/opencds/cqf/servlet/BaseServlet.java
- src/main/java/org/opencds/cqf/servlet/BulkDataServlet.java
- src/test/resources/org/opencds/cqf/bulk-data/group.json
Implemented bulk data export support. Note that this PR does not include the server level operation or the import capabilities.
> Bulk data export

- src/main/java/org/opencds/cqf/providers/CqlExecutionProvider.java
Compilation error due to missing namespace.
> Fixed Parameters reference

- src/main/java/org/opencds/cqf/config/NonCachingLibraryManager.java
- src/main/java/org/opencds/cqf/config/STU3LibraryLoader.java
- src/main/java/org/opencds/cqf/config/STU3LibrarySourceProvider.java
- src/main/java/org/opencds/cqf/evaluation/MeasureEvaluationSeed.java
- src/main/java/org/opencds/cqf/helpers/LibraryHelper.java
- src/main/java/org/opencds/cqf/helpers/LibraryResourceHelper.java
- src/main/java/org/opencds/cqf/providers/CqlExecutionProvider.java
- src/main/java/org/opencds/cqf/providers/FHIRLibraryResourceProvider.java
- src/main/java/org/opencds/cqf/providers/FHIRMeasureResourceProvider.java
- src/main/java/org/opencds/cqf/providers/NarrativeLibraryResourceProvider.java
* Made instances of LibraryLoader thread local
* Removed caching of elm
* Removed caching of source
* Consolidated resolution logic
* Handled loading multiple versions of same library
> Made Library resolution thread local and consolidated resolution logic

- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/MeasureOperationsProvider.java
- r4/src/main/java/org/opencds/cqf/r4/providers/MeasureOperationsProvider.java
> Fix for ordering of measure eval parameters

- r4/src/main/java/org/opencds/cqf/r4/providers/PlanDefinitionApplyProvider.java
> Fix missing annotation for R4 plan definition

- r4/src/main/java/org/opencds/cqf/r4/providers/CqlExecutionProvider.java
- r4/src/main/java/org/opencds/cqf/r4/providers/PlanDefinitionApplyProvider.java
evaluateInContext can now run for either an aliasedExpression or an expression
apply now evaluates actions recursively
action conditions containing a language "text/cql.name" are evaluated with aliasedExpressions
> PlanDefinition apply ersd gaps

- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/JpaTerminologyProvider.java
* Hack to handle versioned value sets
> Cqm sandbox

- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/JpaTerminologyProvider.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/PlanDefinitionApplyProvider.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/servlet/BaseServlet.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/servlet/CdsHooksServlet.java
- pom.xml
- r4/src/main/java/org/opencds/cqf/r4/providers/JpaTerminologyProvider.java
- r4/src/main/java/org/opencds/cqf/r4/providers/PlanDefinitionApplyProvider.java
- r4/src/main/java/org/opencds/cqf/r4/servlet/BaseServlet.java
- r4/src/main/java/org/opencds/cqf/r4/servlet/CdsHooksServlet.java
* Update to cds-hooks release 1.0.3
* Adds support for retrieval by Id
* Adds support for prefetch statements being generated from library data-requirements
> Release 0.1.14.1

- common/src/main/java/org/opencds/cqf/common/config/FhirServerConfig.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/evaluation/MeasureEvaluation.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/JpaTerminologyProvider.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/MeasureOperationsProvider.java
- r4/src/main/java/org/opencds/cqf/r4/evaluation/MeasureEvaluation.java
- r4/src/main/java/org/opencds/cqf/r4/helpers/LibraryHelper.java
- r4/src/main/java/org/opencds/cqf/r4/providers/JpaTerminologyProvider.java
- r4/src/main/java/org/opencds/cqf/r4/providers/LibraryOperationsProvider.java
- r4/src/main/java/org/opencds/cqf/r4/providers/MeasureOperationsProvider.java
* Fixes various warnings and spelling errors in the ruler
> Fix various build warnings

- common/src/main/java/org/opencds/cqf/common/config/FhirServerConfig.java
- common/src/main/java/org/opencds/cqf/common/config/HapiProperties.java
* Added configuration for forcing / ignoring referential integrity checks on delete / write
> Feature allow disable reference checks

- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/QuestionnaireProvider.java
- r4/src/main/java/org/opencds/cqf/r4/providers/QuestionnaireProvider.java
- r4/src/main/resources/hapi.properties
Added code to loop through QR items and answers to be more generic , match the spec, and work with new questionnaireResponse
> loop for items and answers in QuestionnaireResponse extract operation

- common/pom.xml
- cqf-ruler-dstu3/pom.xml
- cqf-ruler-r4/pom.xml
- dstu3/pom.xml
- r4/pom.xml
> Proposed 0.4.0 Release Redux

- dstu3/src/main/java/org/opencds/cqf/dstu3/builders/RequestGroupBuilder.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/helpers/ContainedHelper.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/PlanDefinitionApplyProvider.java
- r4/src/main/java/org/opencds/cqf/r4/builders/RequestGroupBuilder.java
- r4/src/main/java/org/opencds/cqf/r4/helpers/ContainedHelper.java
- r4/src/main/java/org/opencds/cqf/r4/providers/PlanDefinitionApplyProvider.java
* Based on #255 - Thanks @dehall and team!
* Resolved conflicts with latest develop branch
* Ported changes to dstu3
> Mcode requestgroup nestedplandefs

- dstu3/src/main/java/org/opencds/cqf/dstu3/evaluation/MeasureEvaluation.java
- r4/src/main/java/org/opencds/cqf/r4/evaluation/MeasureEvaluation.java
MeasureEvaluation code changes to better handle SupplementalDataElements.
> adjustments to sde code to handle codes in addition to codings

- r4/src/main/java/org/opencds/cqf/r4/evaluation/MeasureEvaluation.java
> Added display to codeToResourceMap

- cqf-ruler-dstu3/src/main/webapp/WEB-INF/jetty-web.xml
- cqf-ruler-r4/src/main/webapp/WEB-INF/jetty-web.xml
- pom.xml
* Import HAPI versions for various dependencies
* Make form size limit larger to allow posting of Measure bundles
> Use HAPI bom for versions, make content size limit larger

- dstu3/src/main/java/org/opencds/cqf/dstu3/evaluation/MeasureEvaluation.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/MeasureOperationsProvider.java
and added evaluatedResources to careGapsReport
> Added populationReference extension to evaluatedResources

- dstu3/src/main/java/org/opencds/cqf/dstu3/evaluation/MeasureEvaluation.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/MeasureOperationsProvider.java
- pom.xml
- r4/src/main/java/org/opencds/cqf/r4/evaluation/MeasureEvaluation.java
- r4/src/main/java/org/opencds/cqf/r4/providers/MeasureOperationsProvider.java
populationReference is now a StringType instead of CodeableConcept
fixed Gaps in care report display
added composition author
set fullUrls for all relativeReferences in Bundle
> updated MeasureReference to use Measure.url

- common/src/main/java/org/opencds/cqf/common/retrieve/JpaFhirRetrieveProvider.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/evaluation/MeasureEvaluation.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/CodeSystemUpdateProvider.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/LibraryOperationsProvider.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/MeasureOperationsProvider.java
- r4/src/main/java/org/opencds/cqf/r4/evaluation/MeasureEvaluation.java
- r4/src/main/java/org/opencds/cqf/r4/providers/CodeSystemUpdateProvider.java
- r4/src/main/java/org/opencds/cqf/r4/providers/LibraryOperationsProvider.java
- r4/src/main/java/org/opencds/cqf/r4/providers/MeasureOperationsProvider.java
> Use synchronous map

- dstu3/src/main/java/org/opencds/cqf/dstu3/config/FhirServerConfigDstu3.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/evaluation/ProviderFactory.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/ActivityDefinitionApplyProvider.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/PlanDefinitionApplyProvider.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/servlet/CdsHooksServlet.java
- dstu3/src/main/resources/hapi.properties
- r4/src/main/java/org/opencds/cqf/r4/config/FhirServerConfigR4.java
- r4/src/main/java/org/opencds/cqf/r4/evaluation/ProviderFactory.java
- r4/src/main/java/org/opencds/cqf/r4/providers/ActivityDefinitionApplyProvider.java
- r4/src/main/java/org/opencds/cqf/r4/providers/PlanDefinitionApplyProvider.java
- r4/src/main/java/org/opencds/cqf/r4/servlet/CdsHooksServlet.java
- r4/src/main/resources/hapi.properties
* Changes the default dbs for dstu3 / r4 to be different
* Updates some named Beans to prevent Spring from getting confused
> Fix shared db, fix spring getting confused

- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/MeasureOperationsProvider.java
- r4/src/main/java/org/opencds/cqf/r4/providers/MeasureOperationsProvider.java
Update ids to reflect subject
Update MeasureReport restriction to be by period, not date
> Move synchronous params after group to patient list

- .vscode/launch.json
- plugin/sdc/src/main/java/org/opencds/cqf/ruler/plugin/sdc/dstu3/ExtractProvider.java
- plugin/sdc/src/main/java/org/opencds/cqf/ruler/plugin/sdc/r4/ExtractProvider.java
- plugin/utility/README.md
- plugin/utility/pom.xml
- plugin/utility/src/main/java/org/opencds/cqf/ruler/plugin/utility/ClientUtilities.java
- plugin/utility/src/main/java/org/opencds/cqf/ruler/plugin/utility/HeaderInjectionInterceptor.java
- plugin/utility/src/main/java/org/opencds/cqf/ruler/plugin/utility/IdUtilities.java
- plugin/utility/src/test/java/org/opencds/cqf/ruler/plugin/utility/ClientUtilitiesTest.java
- plugin/utility/src/test/java/org/opencds/cqf/ruler/plugin/utility/IdUtilitiesTest.java
- pom.xml
* Refactor some helpers into a "utility" plugin
* Some initial tests for same
This PR establishes a new pattern for "helper" or "utility" classes by using default interface implementations. It's similar to extension methods, but at a class level.
> Initial utility plugin

- external/pom.xml
- plugin/hello-world/src/main/java/org/opencds/cqf/ruler/plugin/hello/HelloWorldProvider.java
- plugin/utility/src/main/java/org/opencds/cqf/ruler/plugin/utility/ClientUtilities.java
- plugin/utility/src/main/java/org/opencds/cqf/ruler/plugin/utility/IdUtilities.java
- plugin/utility/src/main/java/org/opencds/cqf/ruler/plugin/utility/ReflectionUtilities.java
- plugin/utility/src/main/java/org/opencds/cqf/ruler/plugin/utility/ResolutionUtilities.java
- plugin/utility/src/main/java/org/opencds/cqf/ruler/plugin/utility/VersionUtilities.java
- plugin/utility/src/test/java/org/opencds/cqf/ruler/plugin/utility/IdUtilitiesTest.java
- pom.xml
* Utilities to id generation, resolving by URL, name and version, and Id.
> Additional utilities for resolving resources

- plugin/cql/src/main/java/org/opencds/cqf/ruler/plugin/cql/CqlConfig.java
Added EmbeddedFhirLibraryContent in LibraryLoaderFactory
Added @Primary annotation on modelResolvers and elmCacheResourceChangeListener
Added a @Bean CqlProperties
> FixesToErrorsFoundTesting

- common/pom.xml
- pom.xml
- r4/src/main/java/org/opencds/cqf/r4/evaluation/MeasureEvaluation.java
Small change to EvaluateMeasure to return Payer SDE as well as the addition of a reference to engine 1.5.1 to resolve a reference error for CQLLibraryReader from last master build
> Added Payer SDE to Evaluate Measure Response

- .vscode/settings.json
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/r4/provider/MeasureEvaluateProvider.java
The point was to add the keywords that were causing problems and suppress another.
The formatting was a side-effect.
> Fix problems

- core/pom.xml
- external/pom.xml
- plugin/cds-hooks/src/test/java/org/opencds/cqf/ruler/plugin/cdshooks/dstu3/CdsHooksServletIT.java
- plugin/cds-hooks/src/test/java/org/opencds/cqf/ruler/plugin/cdshooks/r4/CdsHooksServletIT.java
- test/src/main/java/org/opencds/cqf/ruler/test/RestIntegrationTest.java
> Restore cds-hooks tests

- pom.xml
- scripts/deploy.sh
* Fixed bug in activating release profile during tagged builds
> Fix typo in deploy script

- .vscode/launch.json
- core/pom.xml
- external/pom.xml
- plugin/cr/pom.xml
- pom.xml
* Adds DSTU3 debug profile
* Excludes some transitive engine dependencies that were causing an incorrect version of the engine to be included.
> Exclude transitive engine dependencies

- core/src/main/java/org/opencds/cqf/ruler/Server.java
- core/src/main/java/org/opencds/cqf/ruler/config/TesterUIConfig.java
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/dstu3/provider/DataOperationsProvider.java
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/r4/provider/DataOperationsProvider.java
- server/src/main/webapp/WEB-INF/templates/tmpl-head.html
In reverse proxy scenarios, the js/css/html for the tester UI isn't loaded correctly due to URLs not being relative to the server. This PR fixes that.
> Fix resource references in html templates

- README.md
- core/pom.xml
- core/src/main/java/org/opencds/cqf/ruler/Application.java
- core/src/main/java/org/opencds/cqf/ruler/config/TesterUIConfig.java
- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/CdsHooksConfig.java
- plugin/cql/src/main/java/org/opencds/cqf/ruler/cql/CqlConfig.java
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/r4/provider/PlanDefinitionApplyProvider.java
- server/src/main/resources/application.yaml
* Disable HAPI CQL Provider Factory
* Add test server docs to Readme
* Fix code warnings
> Disable HAPI CqlProviderFactory

- Dockerfile
* Add `apt upgrade` to Dockerfile
* Resolves #494
> Add debian package upgrade to docker images

- plugin/cpg/src/main/resources/application.yaml
- plugin/cql/src/main/java/org/opencds/cqf/ruler/cql/CqlProperties.java
- plugin/cql/src/main/java/org/opencds/cqf/ruler/cql/utility/Translators.java
- plugin/cql/src/main/resources/application.yaml
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/dstu3/provider/DataOperationsProvider.java
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/r4/provider/DataOperationsProvider.java
- plugin/cr/src/test/java/org/opencds/cqf/ruler/cr/CqlBuilder.java
- plugin/cr/src/test/java/org/opencds/cqf/ruler/cr/r4/provider/DataOperationProviderIT.java
Moved the Translators utility from the Core project into the CQL Plugin. Also, modified CR plugin to leverage the CQL plugin and its configuration.
> Moved the Core/utility/Translators class to the CQL Plugin.

- plugin/case-reporting/src/main/java/org/opencds/cqf/ruler/casereporting/CaseReportingProperties.java
- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/CdsHooksProperties.java
- plugin/cpg/src/main/java/org/opencds/cqf/ruler/cpg/CpgProperties.java
- plugin/cql/src/main/java/org/opencds/cqf/ruler/cql/CqlProperties.java
- plugin/cql/src/main/java/org/opencds/cqf/ruler/cql/JpaTerminologyProvider.java
- plugin/cql/src/main/resources/application.yaml
- plugin/cql/src/test/java/org/opencds/cqf/ruler/cql/CqlPropertiesFactory.java
- plugin/cql/src/test/java/org/opencds/cqf/ruler/cql/CqlPropertiesTest.java
- plugin/cql/src/test/resources/application.yaml
- plugin/cr/pom.xml
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/CrProperties.java
- plugin/cr/src/test/java/org/opencds/cqf/ruler/cr/dstu3/ExpressionEvaluationIT.java
- plugin/cr/src/test/java/org/opencds/cqf/ruler/cr/dstu3/provider/ActivityDefinitionApplyProviderIT.java
- plugin/cr/src/test/java/org/opencds/cqf/ruler/cr/dstu3/provider/MeasureEvaluateProviderIT.java
- plugin/cr/src/test/java/org/opencds/cqf/ruler/cr/dstu3/provider/PlanDefinitionApplyProviderIT.java
- plugin/cr/src/test/java/org/opencds/cqf/ruler/cr/r4/ExpressionEvaluationIT.java
- plugin/cr/src/test/java/org/opencds/cqf/ruler/cr/r4/provider/ActivityDefinitionApplyProviderIT.java
- plugin/cr/src/test/java/org/opencds/cqf/ruler/cr/r4/provider/MeasureEvaluateProviderIT.java
- plugin/cr/src/test/java/org/opencds/cqf/ruler/cr/r4/provider/PlanDefinitionApplyProviderIT.java
- plugin/dev-tools/src/main/java/org/opencds/cqf/ruler/devtools/DevToolsProperties.java
- plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/RAProperties.java
- plugin/sdc/src/main/java/org/opencds/cqf/ruler/sdc/SDCProperties.java
- plugin/security/src/main/java/org/opencds/cqf/ruler/security/SecurityProperties.java
- plugin/security/src/main/java/org/opencds/cqf/ruler/security/interceptor/AuthenticationInterceptor.java
- server/src/main/resources/application.yaml
* Fix CQL property binding and tests for same
* Update default properties
* Standardize "isEnabled" convention for property names
> Fix cql property binding

- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/CdsServicesCache.java
Accounting for existing plandefinitions on when initializing cds hooks service cache
> #575: Cds Hooks services cache initialization

- plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/r4/RiskAdjustmentProvider.java
- plugin/ra/src/test/java/org/opencds/cqf/ruler/ra/r4/RiskAdjustmentProviderIT.java
#571 - resolving evidence date with updated design
#577 - changed operation name to $evaluate-risk-condition-category
> Updates to $risk-adjustment

- core/pom.xml
- example/pom.xml
- external/pom.xml
- plugin/case-reporting/pom.xml
- plugin/cds-hooks/pom.xml
- plugin/cpg/pom.xml
- plugin/cql/pom.xml
- plugin/cr/pom.xml
- plugin/dev-tools/pom.xml
- plugin/pom.xml
- plugin/ra/pom.xml
- plugin/sdc/pom.xml
- plugin/security/pom.xml
- pom.xml
- server/pom.xml
- test/pom.xml
completing platform release, needed to set properties of cql engine, tooling, evaluator to 'SNAPSHOT'
> Update properties snapshot

- plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/RAConfig.java
- plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/r4/AssistedServlet.java
- plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/r4/ReportProvider.java
- plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/r4/ResolveProvider.java
- plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/r4/RiskAdjustmentProvider.java
- plugin/ra/src/test/java/org/opencds/cqf/ruler/ra/r4/ReportProviderIT.java
- plugin/ra/src/test/java/org/opencds/cqf/ruler/ra/r4/ResolveProviderIT.java
- plugin/ra/src/test/java/org/opencds/cqf/ruler/ra/r4/RiskAdjustmentProviderIT.java
- plugin/ra/src/test/resources/resolve-test-bundle.json
Updated $report operation to include measureId, measureIdentifier, and measureUrl parameters and return an error if one is not provided.
Updated $report tests
Added servlet for assisted use case (accepts POST request with text/csv header)
Added $resolve operation and tests
> Risk adjustment connectathon updates

- pom.xml
PR to update CQF tooling from snapshot to release version
> Update cqf-tooling to 2.0 from SNAPSHOT-2.0

- pom.xml
to prevent block of uploading staging data to nexus, used profileid from alphorabot
> add staging profileid to nexus upload

- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/request/CdsHooksRequest.java
- plugin/cds-hooks/src/test/java/org/opencds/cqf/ruler/plugin/cdshooks/request/CdsHooksRequestIT.java
Enhancement for #122 
Added jsonproperty setter for expires_in that supports integer or string
Added simple test
> Support for expires_in as string

- example/pom.xml
- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/dstu3/CdsHooksServlet.java
- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/r4/CdsHooksServlet.java
- plugin/cds-hooks/src/test/java/org/opencds/cqf/ruler/plugin/cdshooks/r4/CdsHooksResponseIT.java
- plugin/cds-hooks/src/test/java/org/opencds/cqf/ruler/plugin/cdshooks/response/CdsHooksResponseIT.java
- plugin/cds-hooks/src/test/resources/html-request.json
- plugin/cds-hooks/src/test/resources/library-html.json
- plugin/cds-hooks/src/test/resources/library-unicode.json
- plugin/cds-hooks/src/test/resources/plandefinition-html.json
- plugin/cds-hooks/src/test/resources/plandefinition-unicode.json
- plugin/cds-hooks/src/test/resources/unicode-request.json
Enhancement for #583 
Added unicode charset to CDS Hooks servlet response
Added tests for unicode characters and html content
Added html fix to dstu3 CDS Hooks service
> Unicode character handling for CDS Hooks service

- pom.xml
> Add the nexus-staging plugin to the base build profile

- core/pom.xml
- example/pom.xml
- external/pom.xml
- plugin/case-reporting/pom.xml
- plugin/cds-hooks/pom.xml
- plugin/cpg/pom.xml
- plugin/cql/pom.xml
- plugin/cql/src/main/java/org/opencds/cqf/ruler/cql/CqlConfig.java
- plugin/cr/pom.xml
- plugin/cr/src/test/java/org/opencds/cqf/ruler/cr/CqlBuilder.java
- plugin/dev-tools/pom.xml
- plugin/pom.xml
- plugin/ra/pom.xml
- plugin/sdc/pom.xml
- plugin/security/pom.xml
- pom.xml
- server/pom.xml
- test/pom.xml
PR for release v0.7.0 of the ruler
> update ruler for 0.7.0 release

- core/pom.xml
- example/pom.xml
- external/pom.xml
- plugin/case-reporting/pom.xml
- plugin/cds-hooks/pom.xml
- plugin/cpg/pom.xml
- plugin/cql/pom.xml
- plugin/cr/pom.xml
- plugin/dev-tools/pom.xml
- plugin/pom.xml
- plugin/ra/pom.xml
- plugin/sdc/pom.xml
- plugin/security/pom.xml
- pom.xml
- server/pom.xml
- test/pom.xml
updating master to next snapshot release v0.8.0-SNAPSHOT and updating dependencies to latest snapshots
> updating ruler master to next snapshot

- core/pom.xml
- example/pom.xml
- external/pom.xml
- plugin/case-reporting/pom.xml
- plugin/cds-hooks/pom.xml
- plugin/cpg/pom.xml
- plugin/cql/pom.xml
- plugin/cr/pom.xml
- plugin/dev-tools/pom.xml
- plugin/pom.xml
- plugin/ra/pom.xml
- plugin/sdc/pom.xml
- plugin/security/pom.xml
- pom.xml
- server/pom.xml
- test/pom.xml
Post release of 0.8.0, moving master to latest snapshot 0.9.0-SNAPSHOT
> update to 0.9.0-SNAPSHOT

- plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/RAConstants.java
- plugin/ra/src/test/resources/Bundle-ra-coding-gaps-result-1.json
- plugin/ra/src/test/resources/Bundle-ra-coding-gaps-result-2.json
- plugin/ra/src/test/resources/Bundle-ra-coding-gaps-result-3.json
- plugin/ra/src/test/resources/DetectedIssue-ra-measurereport03-report-110.json
- plugin/ra/src/test/resources/DetectedIssue-ra-measurereport03-report-96.json
Resolution for #661 
Updated the returned Parameters id to `remediate-coding-gaps-<guid>`
> Remediate operation spec update

- core/pom.xml
- example/pom.xml
- external/pom.xml
- plugin/case-reporting/pom.xml
- plugin/cds-hooks/pom.xml
- plugin/cpg/pom.xml
- plugin/cql/pom.xml
- plugin/cr/pom.xml
- plugin/dev-tools/pom.xml
- plugin/pom.xml
- plugin/ra/pom.xml
- plugin/sdc/pom.xml
- plugin/security/pom.xml
- pom.xml
- server/pom.xml
- test/pom.xml
PR to update to snapshot from release v0.9.0
> update to v0.10.0-snapshot

- core/pom.xml
- example/pom.xml
- external/pom.xml
- plugin/case-reporting/pom.xml
- plugin/cds-hooks/pom.xml
- plugin/cpg/pom.xml
- plugin/cql/pom.xml
- plugin/cr/pom.xml
- plugin/dev-tools/pom.xml
- plugin/pom.xml
- plugin/ra/pom.xml
- plugin/sdc/pom.xml
- plugin/security/pom.xml
- pom.xml
- server/pom.xml
- test/pom.xml
> release 0.12.0

- core/pom.xml
- example/pom.xml
- external/pom.xml
- plugin/case-reporting/pom.xml
- plugin/cds-hooks/pom.xml
- plugin/cpg/pom.xml
- plugin/cql/pom.xml
- plugin/cr/pom.xml
- plugin/dev-tools/pom.xml
- plugin/pom.xml
- plugin/ra/pom.xml
- plugin/sdc/pom.xml
- plugin/security/pom.xml
- pom.xml
- server/pom.xml
- test/pom.xml
> snapshot 0.13.0

- plugin/cql/src/main/java/org/opencds/cqf/ruler/cql/KnowledgeArtifactAdapter.java
- plugin/cql/src/main/java/org/opencds/cqf/ruler/cql/KnowledgeArtifactProcessor.java
- plugin/cql/src/main/java/org/opencds/cqf/ruler/cql/RepositoryService.java
- plugin/cql/src/test/java/org/opencds/cqf/ruler/cql/RepositoryServiceTest.java
- plugin/cql/src/test/resources/minimal-draft-to-test-version-conflict.json
I've set the base as `APHL-469-Package-operation` for the purposes of review, since I was using that as the base and didn't realize it contained a whole bunch of unmerged changes
> Aphl 535 Transaction Draft operation, allowing multiple drafts

- .vscode/settings.json
- core/pom.xml
- core/src/main/java/org/opencds/cqf/ruler/config/RulerConfig.java
- core/src/main/java/org/opencds/cqf/ruler/config/ServerProperties.java
- plugin/cr/src/test/java/org/opencds/cqf/ruler/cr/r4/provider/DataOperationProviderIT.java
- pom.xml
- server/pom.xml
- server/src/main/resources/application.yaml
- test/pom.xml
addressing security vulnerabilities and feature for exposing max includes limit to an environment variable
> Feature configure max includes

- plugin/cql/src/main/java/org/opencds/cqf/ruler/cql/RepositoryService.java
- plugin/cql/src/test/java/org/opencds/cqf/ruler/cql/RepositoryServiceTest.java
this should fix the error when trying to approve using a valid target uri
> [APHL-546] fix bad target canonical handling in $approve

- plugin/cpg/src/main/java/org/opencds/cqf/ruler/cpg/CqlEvaluationHelper.java
Added workaround for new FHIRQueryGenerator creation in SearchParamFhirRetrieveProvider
> CDS Hooks FHIRQueryGenerator ValueSet Expansion Configuration for Remote Providers

- .github/workflows/publish-snapshot-vsm-operations.yml
- .github/workflows/publish-snapshot.yml
> [APHL-630] update to ci cd

- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/KnowledgeArtifactProcessor.java
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/RepositoryService.java
- plugin/cr/src/test/java/org/opencds/cqf/ruler/cr/r4/RepositoryServiceTest.java
Whitespace and convention updates
> Aphl 778 package update

- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/CrConfig.java
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/CrRulerProperties.java
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/KnowledgeArtifactProcessor.java
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/TerminologyServerClient.java
- plugin/cr/src/main/resources/application.yaml
- plugin/cr/src/test/java/org/opencds/cqf/ruler/cr/KnowledgeArtifactProcessorIT.java
- plugin/cr/src/test/java/org/opencds/cqf/ruler/cr/KnowledgeArtifactProcessorTest.java
- plugin/cr/src/test/resources/org/opencds/cqf/ruler/cr/r4/test/valueset-expanded.json
- plugin/cr/src/test/resources/org/opencds/cqf/ruler/cr/r4/valueset/valueset-2.16.840.1.113762.1.4.1116.89.json
- plugin/cr/src/test/resources/org/opencds/cqf/ruler/cr/r4/valueset/valueset-vsm-authored.json
https://alphora.atlassian.net/browse/APHL-868
> Add common getExpansion() function

- plugin/cr/src/test/resources/small-expansion-bundle.json
- plugin/cr/src/test/resources/small-naive-expansion-bundle.json
Removed version field from value set compose which should not be present.
> Remove erroneous version field in value set compose
