cqframework/cqf-ruler

- src/main/java/org/opencds/cqf/exceptions/Helper.java
- src/main/java/org/opencds/cqf/providers/FHIREndpointProvider.java
- src/main/java/org/opencds/cqf/providers/FHIRMeasureResourceProvider.java
- src/main/java/org/opencds/cqf/servlet/BaseServlet.java
I made a few changes to the proposed operation. During the design discussion we had proposed an operation on a ValueSet instance, but this is actually an operation on an Endpoint instance (if we were to ship one of the ValueSets stored within the CQF Ruler to another server, then that would be an operation on a ValueSet). Therefore, I changed this operation to Endpoint/$cache-valusets and allow for a comma-delimited list of ValueSet ids as one of the parameters.
Example:
`[base]/Endpoint/example-apelon/$cache-valuesets?valuesets=2.16.840.1.114222.4.11.836,2.16.840.1.113883.3.464.1003.108.12.1011&user=user&pass=pass`
Endpoint/example-apelon:
```
{
"resourceType": "Endpoint",
"id": "example-apelon",
"status": "active",
"connectionType": {
"system": …
```
> Valueset cache operation

- src/main/java/org/opencds/cqf/providers/FHIRMeasureResourceProvider.java
This is the initial iteration of the $collect-data operation. 
It is pretty straight-forward:
1. Run the measure for the specified Patient/Practitioner and period
1. Parse the evaluated resources Bundle 
1. Populate and return the Parameters resource 
There is still an issue. Several of the resources returned from the operation have references to resources that aren't included. The omission of the referenced resources may cause a $submit-data request to fail with the results of the $collect-data operation. This would be a simple fix using the _include=Resource:*, but HAPI doesn't support the use of wildcards.
> Collect data operation

- common/src/main/java/org/opencds/cqf/common/helpers/DateHelper.java
This fixes boundary and display issues with dates when the JVM timezone is not defaulted to 'UTC'.
**To test:**
- Start cqf-ruler on a machine with a default timezone other than UTC. I used US Eastern.
- Upload attached measure with config data.
[EXM124-FHIR3.zip](https://github.com/DBCG/cqf-ruler/files/4031337/EXM124-FHIR3.zip)
- ```curl -v  "http://localhost:8080/cqf-ruler-dstu3/fhir/Measure/measure-exm124-FHIR3/%24evaluate-measure?patient=98ce13e-450b-43ca-9fbe-08b05999532b-1&periodStart=2019-01-01&periodEnd=2019-12-31" -H "Content-Type: application/json"```
**Boundary issues:** 
**Before:**
```
{
"code": {
"coding": [
{
"system": "http://terminology.hl7.org/CodeSystem/measure-population",
"code": "numerator",
"display": "Numerator"
}
]
},
"count": 0
},
```
**After:**
```
{
"code": { …
```
> Added code to set timezone to UTC to fix boundary and display issues in $evaluate-measure

- dstu3/src/main/java/org/opencds/cqf/dstu3/evaluation/MeasureEvaluation.java
- r4/src/main/java/org/opencds/cqf/r4/evaluation/MeasureEvaluation.java
* Resolves #153 by resetting the expression cache between patients.
This is a workaround since there's a forthcoming Measure evaluation refactor that avoids this problem.
> Reset expression cache when context parameters change

- r4/src/main/java/org/opencds/cqf/r4/providers/ActivityDefinitionApplyProvider.java
- r4/src/main/java/org/opencds/cqf/r4/providers/PlanDefinitionApplyProvider.java
Improve reliability of dynamicType setting. Also expands support for CommunicationRequest and adds Task as result resources.
> Add dynamicValue error checking and type conversion

- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/MeasureOperationsProvider.java
- r4/src/main/java/org/opencds/cqf/r4/providers/MeasureOperationsProvider.java
> Add id to Parameters

- dstu3/src/main/java/org/opencds/cqf/dstu3/servlet/CdsHooksServlet.java
- r4/src/main/java/org/opencds/cqf/r4/servlet/CdsHooksServlet.java
For issue 38 - comparing hook.getRequest().getHook() with planDefinition triggers to make sure the hooks match. If not then throw an exception.
Please make sure I am comparing the right things. I might be totally off base.
> 38 hook match service

- common/src/main/java/org/opencds/cqf/common/config/HapiProperties.java
- common/src/main/java/org/opencds/cqf/common/helpers/LoggingHelper.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/evaluation/MeasureEvaluationSeed.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/ApplyCqlOperationProvider.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/providers/CqlExecutionProvider.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/servlet/CdsHooksServlet.java
- dstu3/src/main/resources/hapi.properties
- dstu3/src/main/resources/logback.xml
- r4/src/main/java/org/opencds/cqf/r4/evaluation/MeasureEvaluationSeed.java
- r4/src/main/java/org/opencds/cqf/r4/providers/ApplyCqlOperationProvider.java
- r4/src/main/java/org/opencds/cqf/r4/providers/CqlExecutionProvider.java
- r4/src/main/java/org/opencds/cqf/r4/providers/LibraryOperationsProvider.java
- r4/src/main/java/org/opencds/cqf/r4/servlet/CdsHooksServlet.java
- r4/src/main/resources/hapi.properties
- r4/src/main/resources/logback.xml
Make DebugMap configurable where used in ruler
> Config log

- common/src/main/java/org/opencds/cqf/common/config/HapiProperties.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/evaluation/MeasureEvaluationSeed.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/servlet/CdsHooksServlet.java
- dstu3/src/main/resources/hapi.properties
- dstu3/src/main/resources/logback.xml
- pom.xml
- r4/src/main/java/org/opencds/cqf/r4/evaluation/MeasureEvaluationSeed.java
- r4/src/main/java/org/opencds/cqf/r4/servlet/CdsHooksServlet.java
- r4/src/main/resources/hapi.properties
- r4/src/main/resources/logback.xml
contains updates to facilitate turning CQL debug logging on and off via a new 'cql.debugLogging.enabled' property in hapi.properties.
also added a logger config to logback.xml to turn DEBUG logging on for org.opencds.cqf.cql.engine.debug.DebugUtilities, the class that's responsible for writing CQL debug logs (this simplifies configuration by not requiring modifications to both hapi.properties and logback.xml when CQL debug logging is desired, now it only needs to be adjusted in one place).
> Feature configurable cql logging

- common/src/main/java/org/opencds/cqf/common/config/FhirServerConfig.java
- dstu3/src/main/java/org/opencds/cqf/dstu3/servlet/CdsHooksServlet.java
- r4/src/main/java/org/opencds/cqf/r4/helpers/LibraryHelper.java
- r4/src/main/java/org/opencds/cqf/r4/servlet/CdsHooksServlet.java
* Cache service definitions
* 3-4x speedup for cds-hooks calls
> Cache cds-service definitions

- plugin/cql/src/main/java/org/opencds/cqf/ruler/plugin/cql/JpaLibraryContentProvider.java
- plugin/cql/src/main/java/org/opencds/cqf/ruler/plugin/cql/LibraryUtilities.java
- plugin/utility/src/main/java/org/opencds/cqf/ruler/plugin/utility/ReflectionUtilities.java
Use IBase instead of IBaseResource in order to capture the ElementDefinition of "Attachment" when getting the content of a Library
> FixesToLibraryContentReflection

- cqf-ruler-dstu3/src/main/webapp/WEB-INF/classes/logback.xml
- cqf-ruler-r4/src/main/webapp/WEB-INF/classes/logback.xml
- dstu3/src/main/resources/logback.xml
- r4/src/main/resources/logback.xml
https://logback.qos.ch/manual/filters.html
The following deny all events with a level below INFO, that is TRACE and DEBUG 
`<filter class="ch.qos.logback.classic.filter.ThresholdFilter">
<level>INFO</level>
</filter>`
The log levels:
.........................
/** No events will be logged.
*/
OFF(0),
/**
* A severe error that will prevent the application from continuing.
*/
FATAL(100),
/**
* An error in the application, possibly recoverable.
*/
ERROR(200),
/**
* An event that might possible lead to an error.
*/
WARN(300),
/**
* An event for informational purposes.
*/
INFO(400),
/**
* A general debugging event.
*/
DEBUG(500),
/**
* A fine-grained debug message, typically capturing the flow through the application.
*/
TRACE(600),
/**
* All events should be logged.
*/
ALL(Integer.MAX_VALUE);
> justify filter thresh hold

- plugin/case-reporting/src/main/java/org/opencds/cqf/ruler/casereporting/CaseReportingConfig.java
- plugin/case-reporting/src/main/java/org/opencds/cqf/ruler/casereporting/r4/ProcessMessageProvider.java
* Remove the `Component` annotation from the r4 process message provider
* Add that provider to the config
* closes #460
> Resolve #460 - Don't register r4 providers in dstu3 mode

- .vscode/launch.json
- Dockerfile
* JDK 17+ contains improvements that allows the JVM to be container aware improving performance in some deployments
> Update Docker image to Java 18 for container-aware improvements

- plugin/cpg/src/main/java/org/opencds/cqf/ruler/cpg/dstu3/provider/CqlExecutionProvider.java
- plugin/cpg/src/main/java/org/opencds/cqf/ruler/cpg/r4/provider/CqlExecutionProvider.java
- plugin/cpg/src/test/java/org/opencds/cqf/ruler/cpg/dstu3/provider/CqlExecutionProviderIT.java
- plugin/cpg/src/test/java/org/opencds/cqf/ruler/cpg/r4/provider/CqlExecutionProviderIT.java
> #537 - extending $cql operation, adding tests, cleanup

- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/evaluation/EvaluationContext.java
- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/evaluation/EvaluationHelper.java
- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/hooks/BaseHookEvaluator.java
- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/r4/CdsHooksServlet.java
- plugin/cds-hooks/src/test/java/org/opencds/cqf/ruler/plugin/cdshooks/r4/CdsHooksServletIT.java
- plugin/cds-hooks/src/test/resources/opioidcds-08-medication.json
- plugin/cds-hooks/src/test/resources/opioidcds-08-patient.json
- plugin/cds-hooks/src/test/resources/opioidcds-08-request-prefetch.json
- plugin/cds-hooks/src/test/resources/opioidcds-08-request.json
Also cleaned up the data provider resolution and moved to the evaluation context.
> Added cds hooks tests for requests with and without prefetch data 

- plugin/cpg/src/main/java/org/opencds/cqf/ruler/cpg/CqlEvaluationHelper.java
- plugin/cpg/src/main/java/org/opencds/cqf/ruler/cpg/dstu3/provider/CqlExecutionProvider.java
- plugin/cpg/src/main/java/org/opencds/cqf/ruler/cpg/dstu3/provider/LibraryEvaluationProvider.java
- plugin/cpg/src/main/java/org/opencds/cqf/ruler/cpg/r4/provider/CqlExecutionProvider.java
- plugin/cpg/src/main/java/org/opencds/cqf/ruler/cpg/r4/provider/LibraryEvaluationProvider.java
- plugin/cpg/src/test/java/org/opencds/cqf/ruler/cpg/dstu3/provider/CqlExecutionProviderIT.java
- plugin/cpg/src/test/java/org/opencds/cqf/ruler/cpg/dstu3/provider/LibraryEvaluationProviderIT.java
- plugin/cpg/src/test/java/org/opencds/cqf/ruler/cpg/r4/provider/CqlExecutionProviderIT.java
- plugin/cpg/src/test/java/org/opencds/cqf/ruler/cpg/r4/provider/LibraryEvaluationProviderIT.java
- plugin/cpg/src/test/resources/org/opencds/cqf/ruler/cpg/dstu3/provider/ErrorLibrary.json
- plugin/cpg/src/test/resources/org/opencds/cqf/ruler/cpg/dstu3/provider/SimpleDstu3Library.json
- plugin/cpg/src/test/resources/org/opencds/cqf/ruler/cpg/r4/provider/ErrorLibrary.json
Returning OperationOutcome when evaluation results in an exception
Removing library from cache before evaluation
> Updated cpg operations error reporting and cache management

- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/r4/CdsHooksServlet.java
Return cards were encoding such things as < br / >, not allowing cards to display as markdown. Disabled HTML Escaping in call to GsonBuilder.
> disabled html coding for return cards in cdshooks

- plugin/cql/src/main/java/org/opencds/cqf/ruler/cql/JpaTerminologyProvider.java
- plugin/cql/src/test/java/org/opencds/cqf/ruler/cql/JpaTerminologyProviderIT.java
- plugin/cql/src/test/resources/valueset-event-status-3.0.2.json
- plugin/cql/src/test/resources/valueset-event-status-4.3.0.json
- plugin/cql/src/test/resources/valueset-filter-comparator.json
- plugin/cql/src/test/resources/valueset-hospice-finding.json
- plugin/cql/src/test/resources/valueset-hospice-procedure.json
- plugin/cql/src/test/resources/valueset-opioid-analgesics-with-ambulatory-misuse-potential.json
- plugin/cql/src/test/resources/valueset-opioidcds-indicator.json
- plugin/cql/src/test/resources/valueset-ucum-common.json
Fix for Zendesk ticket `#3659`
> Updated JpaTerminologyProvider to support expansion with version and code system bindings

- docker-compose.yml
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/CrConfig.java
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/dstu3/provider/MeasureEvaluateProvider.java
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/dstu3/service/MeasureService.java
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/r4/provider/MeasureEvaluateProvider.java
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/r4/service/MeasureService.java
Resolves #638 
Quick n' dirty to unblock some downstream requirements. The MeasureService should really be refactored such that the FactoryLogic is externalized since we are instantiating it per-request. We have some refactoring stories on the backlog that should cover that.
> Refactor Measure logic into a service

- pom.xml
Until there is a new version of the hapi-fhir-jpaserver-starter we need to force version 1.10.0 of Apache Commons Text
> Force newer version of commons-text

- plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/RAConfig.java
- plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/RAConstants.java
- plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/RAProperties.java
- plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/r4/RACodingGapsProvider.java
- plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/r4/RiskAdjustmentUser.java
- plugin/ra/src/main/resources/application.yaml
- plugin/ra/src/test/java/org/opencds/cqf/ruler/ra/r4/RACodingGapsProviderIT.java
- plugin/ra/src/test/resources/AlphoraAuthor-organization.json
Resolution for #660 
Renamed operation from $ra.report to $ra.coding-gaps
Removed codingGapType extension from generated DetectedIssue resources
Renamed codingGapType extension to codingGapRequest
Updated the returned Parameters id to `coding-gaps-<guid>`
Added author and title to generated Composition
> Report operation spec update

- plugin/ra/pom.xml
- plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/RAConstants.java
- plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/r4/AssistedRowData.java
- plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/r4/AssistedServlet.java
- plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/r4/RemediateProvider.java
- plugin/ra/src/test/java/org/opencds/cqf/ruler/ra/r4/AssistedProviderIT.java
- plugin/ra/src/test/resources/org/opencds/cqf/ruler/ra/r4/test.csv
Resolution for #671 
Initial implementation of the assisted servlet functionality.
May need some hardening and additional tests for edge cases.
> Assisted MeasureReport (CSV) operation implementation

- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/CdsHooksProperties.java
- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/dstu3/CdsHooksServlet.java
- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/providers/ProviderConfiguration.java
- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/r4/CdsHooksServlet.java
- plugin/cds-hooks/src/main/resources/application.yaml
- plugin/cql/src/main/java/org/opencds/cqf/ruler/cql/CqlConfig.java
- plugin/cql/src/main/java/org/opencds/cqf/ruler/cql/JpaFhirRetrieveProvider.java
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/r4/provider/DataOperationsProvider.java
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/utility/DataRequirements.java
- server/src/main/resources/application.yaml
Added the queryBatchThreshold configuration point. Made the DataOperationsProvider and DataRequirements aware of the configuration so that it can be passed to the FhirQueryGenerator.
> Feature cql 849

- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/CdsHooksProperties.java
- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/dstu3/CdsHooksServlet.java
- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/providers/ProviderConfiguration.java
- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/r4/CdsHooksServlet.java
- plugin/cds-hooks/src/main/resources/application.yaml
- server/src/main/resources/application.yaml
The OAuth 2.0 `client_id` header may be required to request access to patient data. This PR provides the default `client_id` header name along with a way to configure that to be environment-specific (like Epic-Client-ID for instance). See the [CDSHooks docs](https://cds-hooks.hl7.org/1.0/#passing-the-access-token-to-the-cds-service) for more information, especially the `subject` element in the fhirAuthorization request parameter.
> Added client_id OAuth 2.0 support to CDSHooks service

- core/pom.xml
- example/pom.xml
- external/pom.xml
- plugin/case-reporting/pom.xml
- plugin/cds-hooks/pom.xml
- plugin/cpg/pom.xml
- plugin/cql/pom.xml
- plugin/cr/pom.xml
- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/JpaCRFhirDal.java
- plugin/dev-tools/pom.xml
- plugin/pom.xml
- plugin/ra/pom.xml
- plugin/sdc/pom.xml
- plugin/security/pom.xml
- pom.xml
- server/pom.xml
- test/pom.xml
bug in fhirDal's searchByURL where users that had canonical references were prevented from having them recognized properly.
adding next snapshot for project
leaving cql support versions at release until 3.0 is ready:
```
<cqframework.version>2.7.0</cqframework.version>
<cql-engine.version>2.7.0</cql-engine.version>
<cql-evaluator.version>2.6.0</cql-evaluator.version>
```
> Fhirdal searchbyurl add version

- plugin/cql/src/main/java/org/opencds/cqf/ruler/cql/KnowledgeArtifactProcessor.java
- plugin/cql/src/test/java/org/opencds/cqf/ruler/cql/RepositoryServiceTest.java
$approve was saving the `date` parameter with a higher precision than the `approvalDate` parameter causing $release to fail
> $approve fixed and new test added to ensure it won't block $release

- plugin/cds-hooks/src/main/java/org/opencds/cqf/ruler/cdshooks/r4/CdsHooksServlet.java
Updated cds hooks processing to check for action.priority codes to set card indicator value. This rationale for this functionality/mapping can be found [here](http://hl7.org/fhir/R4/clinicalreasoning-cds-on-fhir.html#evaluation) (navigate to the mapping table in that section with headers "CDS Hooks Element" and "FHIR Resource Mapping")
> CDS Hooks R4 Indicator Resolution

- .gitmodules
- pom.xml
Current master is pointed at 6.7.x-snapshot of hapi-fhir, in order to perform a release we will require the latest release jar of hapi-fhir which is 6.6.1. This also updated external jpaserver-starter project to point at a build with hapi 6.6.1
> Hapi 6.6.1 update

- pom.xml
The added dependency is needed to support SQL Server users. It is a nice QoL enhancement for users that we may want to expand upon and document.
> Adding needed mssql dependency for SQL Server support

- plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/KnowledgeArtifactProcessor.java
CQF Ruler changes for https://alphora.atlassian.net/browse/APHL-907
Existing test data does not contain this extension URL but PRs for artifact diff and package operation changes will need to have test data updated after this is merged.
> Update expansion parameters URL as per CRMI Manifest Library Profile Specification

- plugin/case-reporting/src/main/java/org/opencds/cqf/ruler/casereporting/TransformProperties.java
- plugin/case-reporting/src/main/java/org/opencds/cqf/ruler/casereporting/r4/ImportBundleProducer.java
- plugin/case-reporting/src/test/java/org/opencds/cqf/ruler/casereporting/TransformProviderIT.java
Add group type to groupers that do not have them while importing through $ersd-v2-import operation
> APHL-913-add_grouper_type_use_context
